---

- name: Download Apache Kafka
  get_url:
    url: "{{ kafka_download_base_url }}/{{ kafkaVersion }}/kafka_{{ kafkaScalaVersion }}-{{ kafkaVersion }}.tgz"
    dest: /tmp

- name: unarchive kafka
  unarchive:
    src: "{{ kafkaTarLocation }}"
    dest: "{{ kafkaInstallDir }}"
    copy: no
    owner: "{{ kafkaUser }}"
    group: "{{ kafkaGroup }}"
    validate_certs: false
    keep_newer: yes
    creates: "{{ kafkaInstallDir }}/kafka_{{ kafkaScalaVersion }}-{{ kafkaVersion }}/bin"

- name: Ensuring permissions on unarchieved files
  ansible.builtin.file:
    path: "{{ kafkaInstallDir }}/kafka_{{ kafkaScalaVersion }}-{{ kafkaVersion }}"
    owner: "{{ kafkaUser }}"
    group: "{{ kafkaGroup }}"
    recurse: true
    mode: 0775
